### PR TITLE
Update for SQLAlchemy 1.3+ and use modern Python versions

### PR DESCRIPTION
**Pull request by achimnol**

### CODE REVIEW

**Review by dahlia — COMMENTED** [review]
Thanks for your contribution! Could you update CHANGES.rst file as well?

**Review by dahlia — APPROVED** [review]

**Comment by dahlia** [comment]
I don't have permission to merge PRs…

@pbzweihander @Jhuni0123 Could you review and merge this if it's fine?

**Review by pbzweihander — APPROVED** [review]
Thank you for the great PR!

**Comment by pbzweihander** [comment]
@dahlia I don't have permission to upload a new release to PyPI... :sweat_smile:

**Comment by dahlia** [comment]
@pbzweihander Sorry for my late response. 😢 I've just added `dev_spoqa` to the collaborators on PyPI.

**Comment by kanghyojun** [comment]
Thanks for your works @pbzweihander

**Pull request merged**
